[TS-1225] Session managament based on NextExpectedSeqNum
th2-net/th2-conn-dirty-fix pull request #13
Opened 2023-01-17 15:34 UTC by isengrims

2023-01-18 11:44 UTC, ivandruzhinin requested changes

2023-01-18 11:44 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +    private void setHeader(StringBuilder stringBuilder, String msgType, Integer seqNum, Boolean possDup) {
> Boolean possDup

It's always `false`

2023-01-18 11:44 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandlerSettings.java
> +    private Boolean maintainSessionBasedOnNextExpectedSeqNumber = false;
Maybe rename to `useNextExpectedSeqNum`/`checkNextExpectedSeqNum`?

2023-01-18 11:44 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandlerSettings.java
> +    private String startOfADayTime;
> private String startOfADayTime

Maybe rename to `sessionStartTime`?
And we should also have `sessionEndTime` setting too
Also I guess we can change its type to `LocalTime` - Jackson should be able to handle that (maybe certain annotations will be required)

2023-01-18 11:44 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/SequenceHolder.java
> + * Copyright 2022-2023 Exactpro (Exactpro Systems Limited)
```suggestion
 * Copyright 2023 Exactpro (Exactpro Systems Limited)
```

2023-01-18 11:44 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/util/Util.java
> + * Copyright 2022-2023 Exactpro (Exactpro Systems Limited)
```suggestion
 * Copyright 2023 Exactpro (Exactpro Systems Limited)
```

2023-01-18 11:44 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/util/Util.java
> +        BufferedWriter bw = new BufferedWriter(new FileWriter(filePath));
> BufferedWriter bw = new BufferedWriter(new FileWriter(filePath))

Should be wrapped in "try-with-resources"

2023-01-18 11:44 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            }
Why are we delaying it? This delay could prevent us from saving sequences in time when this method is called from `close` method

2023-01-18 13:27 UTC, ivandruzhinin requested changes

2023-01-18 13:27 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
>              LocalDateTime scheduleTime;
I guess we still should treat startTime/endTime as UTC

2023-01-18 13:27 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            executorService.scheduleAtFixedRate(() -> reset(settings.getSessionEndTime() == null), time, 24, TimeUnit.HOURS);
> settings.getSessionEndTime() == null

I think we should make `sessionEndTime` mandatory if `sessionStartTime` is present

> reset(settings.getSessionEndTime() == null)

We shouldn't not only reset seqnums at start time but also send login

> time, 24, TimeUnit.HOURS

`time` is in milliseconds

2023-01-18 13:27 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +                sendingTime.insertNext(POSS_DUP_TAG, IS_POSS_DUP);
Why do we always set `PossDupTag` to `Y`?

2023-01-18 13:27 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandlerSettings.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HH:mm:ss.SSS")
> HH:mm:ss.SSS

Second and millisecond parts can be optional

2023-01-18 14:29 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> -                    msgSeqNum.incrementAndGet();
Why it was removed?

2023-01-18 14:29 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +        setHeader(logon, MSG_TYPE_LOGON, msgSeqNum.incrementAndGet());
> msgSeqNum.incrementAndGet()

MsgSeqNum should be incremented only after successful login

2023-01-18 14:29 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            enabled.set(false);
Why do we need to delay it? Can we set it right away?

2023-01-20 10:00 UTC, ivandruzhinin requested changes

2023-01-20 12:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            long time = now.until(scheduleTime, ChronoUnit.MINUTES);
> ChronoUnit.MINUTES

Let's narrow it down to seconds

2023-01-20 12:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/util/FileDeserializer.java
> +public class FileDeserializer extends StdDeserializer<File> {
Jackson has built-in deserialzier for `File` (see `FromStringDeserializer`) which will be applied automatically

2023-01-23 11:31 UTC, ivandruzhinin commented on README.md
> ++ *stateFilePath* - path to file where sequences will be saved to use with next login attempts. It is useful when acceptor is not support sequence reset. (`nullable`)
```suggestion
+ *stateFilePath* - path to file where sequences will be saved to use with next login attempts. It is useful when acceptor does not support sequence reset. (`nullable`)
```

2023-01-23 11:31 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            if(settings.getSessionStartTime().isBefore(settings.getSessionEndTime())) {
> if(settings.getSessionStartTime().isBefore(settings.getSessionEndTime())) {

This'll have false positives for some cases (e.g. when start is at `08:00` and end is at `02:00` (of the next day))

2023-01-23 11:31 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
>          if (seqNumValue != null && (gapFillFlagValue == null || requireNonNull(gapFillFlagValue.getValue()).equals("N"))) {
> if (seqNumValue != null && (gapFillFlagValue == null || requireNonNull(gapFillFlagValue.getValue()).equals("N")))

This is fully covered by the next if-block

2023-01-23 11:31 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            executorService.scheduleAtFixedRate(this::reset, time, 24 * 60 * 60, TimeUnit.MINUTES);
> 24 * 60 * 60

Can be extracted into a constant

2023-01-23 11:31 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            executorService.scheduleAtFixedRate(this::close, time, 24 * 60 * 60, TimeUnit.MINUTES);
We should also block message-send attempts when session is inactive

2023-02-01 11:32 UTC, ivandruzhinin approved these changes

2023-03-29 13:28 UTC, isengrims commented
Already merged into dev-version-0 and dev-version-1

2023-03-29 13:28 UTC, closed without merging