[TH2-4680] Adding SendingDateTimeFormat to custom-config
th2-net/th2-conn-dirty-fix pull request #33
Opened 2023-02-28 09:17 UTC by kakhaberakhvlediani

2023-02-28 14:05 UTC, ivandruzhinin requested changes
Please also:
 * add description of this new setting into readme
 * bump version in readme and gradle.properties
 * add description of what's changed in this version into changelog in readme

2023-02-28 14:05 UTC, ivandruzhinin commented on src/test/java/com/exactpro/th2/FixHandlerTest.java
> +    private final FixHandler originalFixHandler;
Why it is here? As I see it used only in 2 methods - it can moved out of `Channel` or even created in-place in these 2 methods

2023-02-28 17:14 UTC, kakhaberakhvlediani commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            formatter = DateTimeFormatter.ofPattern(FIX_DATE_TIME_FORMAT_MS);
You mean DateTimeFormatter or the format itself(FIX_DATE_TIME_FORMAT_MS)?

2023-03-02 09:36 UTC, ivandruzhinin requested changes

2023-03-02 09:36 UTC, ivandruzhinin commented on README.md
> +    connection-type: grpc-client
Please roll this back

2023-03-02 09:36 UTC, ivandruzhinin commented on README.md
> ++ *sendingDateTimeFormat* - DateTime format for outgoing messages. (`nullable`)
```suggestion
+ *sendingDateTimeFormat* - `SendingTime` field format for outgoing messages. (`nullable`)
```

2023-03-02 09:36 UTC, ivandruzhinin commented on README.md
> ++ *sendingDateTimeFormat* - DateTime format for outgoing messages. (`nullable`)
Please also specify default value for this option

2023-03-02 09:36 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            formatter = DateTimeFormatter.ofPattern(FIX_DATE_TIME_FORMAT_MS);
Yeah, I meant DateTimeFormatter itself - to avoid cost of creating it every time

2023-03-13 07:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/FixHandler.java
>          }
We can make `DEFAULT_FORMATTER` a default value for `sendingDateTimeFormat` option to avoid this branch at all

2023-03-13 08:34 UTC, ivandruzhinin approved these changes
Please merge with squash and correct result commit message and description

2023-03-13 09:24 UTC, merged