Remove race condition between maintance messages and other messages.
th2-net/th2-conn-dirty-fix pull request #50
Opened 2023-06-28 12:26 UTC by isengrims

2023-07-06 07:52 UTC, Nikita-Smirnov-Exactpro requested changes

2023-07-06 07:52 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/FixHandler.java
> +            connectivityMaintenanceLock.unlock();
```suggestion
            connectivityMaintenanceLock.unlock();
            recoveryLock.unlock();
```

2023-07-06 07:52 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/FixHandler.java
> +        }
Maybe calling clock/unlock on the connectivityMaintenanceLock is skipped?

2023-07-12 12:43 UTC, Nikita-Smirnov-Exactpro approved these changes

2023-09-15 11:52 UTC, isengrims commented
Removed as maintenance lock looks like unessesary overhead. Moved to: https://github.com/th2-net/th2-conn-dirty-fix/tree/reset_heartbeats_v2

2023-09-15 11:52 UTC, closed without merging