[TH2-4991] Optional book per session configuration
th2-net/th2-conn-dirty-fix pull request #51
Opened 2023-07-18 08:32 UTC by isengrims

2023-07-18 11:05 UTC, Nikita-Smirnov-Exactpro approved these changes

2023-07-18 11:20 UTC, Nikita-Smirnov-Exactpro requested changes
th2-conn-dev-tcp-core has problem

2023-07-21 14:14 UTC, Nikita-Smirnov-Exactpro approved these changes

2024-06-19 08:32 UTC, OptimumCode commented on build.gradle
> +    implementation'com.exactpro.th2:conn-dirty-tcp-core:3.6.0-TH2-4991-+'
chore: should be updated to the proper release version

2024-06-20 07:04 UTC, merged